### ISSUE TITLE
Support of lower versions of php

### ISSUE THREAD

**Issue by hakastein** [php-ecma-intl/ext#19]
PHP 8.2 is not as widespread in the world as at least 8.0, the library looks extremely useful, but the version limitation will greatly reduce its prevalence

So please lower the requirements to at least 8.0,

**Comment by ramsey** [comment]
This extension uses enums, which are available starting in PHP 8.1. Additionally, there are some Zend API features this extension uses that were not introduced until PHP 8.2. As a result, I'm not able to lower the requirements to 8.0.
