### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by remicollet** [php-ecma-intl/ext#3]
Building against PHP 8.2.9 and using GCC 12

```
/tmp/ext/src/ecma402/language_tag.cpp: In function '{anonymous}::VariantCode {anonymous}::parseVariantCode(const std::string&)':
/tmp/ext/src/ecma402/language_tag.cpp:511:26: error: field 'characters' has incomplete type 'std::array<unsigned char, 8>'
  511 |     std::array<LChar, 8> characters{};
      |                          ^~~~~~~~~~
In file included from /usr/include/c++/12/bits/hashtable_policy.h:34,
                 from /usr/include/c++/12/bits/hashtable.h:35,
                 from /usr/include/c++/12/unordered_set:46,
                 from /tmp/ext/src/ecma402/language_tag.cpp:20:
/usr/include/c++/12/tuple:1595:45: note: declaration of 'struct std::array<unsigned char, 8>'
 1595 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
/tmp/ext/src/ecma402/language_tag.cpp:515:37: error: static assertion failed: size must be equal
  515 |   static_assert(sizeof(VariantCode) == sizeof(Code), "size must be equal");
      |                 ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~

```

**Comment by ramsey** [comment]
I borrowed this from WebKit, but it looks like I might need to rework a few things.

Here are the same lines from WebKit: https://github.com/WebKit/WebKit/blob/6d13b1672d0f7ce5a6f8093e1ed597e0bd0f2cf2/Source/JavaScriptCore/runtime/IntlObject.cpp#L1148-L1152

`VariantCode` is a `uint64_t`, while `Code` is:

```c
  struct Code {
    std::array<LChar, 8> characters{};
  };
```

And `LChar` is `unsigned char`.

I think what's happening here is largely a result of my lack of understanding about that assertion. Maybe WebKit wants to force use of a specific set of compilers where these values would have the same size?

Should I remove the assertions and rely on the compilers to do the right thing, or should I change the data types here to be less specific? Maybe just use `int` instead?
